### ISSUE TITLE
Undefined method '+' for :Hash

### ISSUE THREAD

**Issue by dannysmith** [IvanShamatov/sinatra-soap#4]
I've just tried to use this on a project (with a view to saving me the massive ball-ache of building a SOAP service!) and encountered this error:

![screen shot 2014-05-22 at 23 59 21](https://cloud.githubusercontent.com/assets/28115/3061316/c208904c-e204-11e3-9acf-10e500caa501.png)

A clean project with this:

``` ruby
require 'sinatra/base'
require 'sinatra/soap'

class SoapAPI < Sinatra::Base

  #remember to register extenstion if you are using modular style
  register Sinatra::Soap

  soap :test, in: { thing: :string }, out: nil do
    {thing: "My thing"}
  end
end
```

yields the same error. All the tests seem to pass, and I haven't got time to dig any deeper right now.  

What's `formats[:in] + formats[:out]` supposed to do to the hashes? I'm afraid I'm not very well versed in builder's DSL.

**Comment by shiftux** [comment]
This is still not fixed in the gem.
adding this line to my Gemfile worked for me:
`gem 'sinatra-soap', github: 'IvanShamatov/sinatra-soap'`
hth

**Comment by dannysmith** [comment]
@shiftux I never bumped the version number in #5. You could bump it yourself and ask @IvanShamatov to merge and push a new release to RubyGems.

**Comment by IvanShamatov** [comment]
@shiftux sure, I can do that. 
By the way, are you sure it is implemented in gem already? Cause I worked on documentation but I hardly spent some time to implement all this stuff inside. 
@dannysmith @shiftux Guys, there is no problem to transfer this gem to anyone of you, if you agree to complete it.

**Comment by dannysmith** [comment]
The last commit on here is when you merged #5 back in 2014. The latest version on rubygems is from Dec 2014. More than happy to bump the version number and push a new release to rubygems if you transfer it to me on both, but I can't really commit to maintaining it properly since I don't know much about SOAP! @IvanShamatov let me know what you want to do.

**Comment by IvanShamatov** [comment]
@dannysmith just make a pull request, I will push it to rubygems, if it works

**Comment by IvanShamatov** [comment]
@dannysmith And thanks for help.

**Comment by dannysmith** [comment]
Cool. I'll raise a PR for the version number tomorrow, which will also close #6.

@IvanShamatov Do you want me to include [this commit](https://github.com/mkonecny/sinatra-soap/commit/3745646178b79f6ed16e75213e33e7d02a16718e) (which is unrelated)?

**Comment by shiftux** [comment]
thanks to both of you @dannysmith, @IvanShamatov 
i am not at all versed in the use of SOAP, i would not feel comfortable taking over this gem
but happy to help if i can
